# Generated by Django 6.0.2 on 2026-03-06 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartline', '0003_alter_bpentry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BPJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('subject', models.CharField(max_length=200)),
                ('journal', models.TextField()),
                ('mood', models.CharField(choices=[('super_good', 'Super Good'), ('fine', 'Fine'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('sad', 'Sad')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
